import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/core/header";
import {ClerkProvider} from '@clerk/nextjs'
import { CreateEventDrawer } from "@/components/core/create-event";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <div className="min-h-screen bg-gradient-to-br from-white to-orange-200">{children}</div>
        <footer>

        </footer>
        <CreateEventDrawer />
      </body>
    </html>
    </ClerkProvider>
  );
}
